{"code":"23505","constraint":"pg_class_relname_nsp_index","detail":"Key (relname, relnamespace)=(users_id_seq, 2200) already exists.","file":"nbtinsert.c","length":255,"level":"error","line":"673","message":"Error initializing database tables: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","service":"devquery-backend","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:43:7)","table":"pg_class","timestamp":"2025-07-31 15:08:50"}
{"code":"23505","constraint":"pg_class_relname_nsp_index","detail":"Key (relname, relnamespace)=(user_sessions_id_seq, 2200) already exists.","file":"nbtinsert.c","length":263,"level":"error","line":"673","message":"Error initializing database tables: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","service":"devquery-backend","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:82:7)","table":"pg_class","timestamp":"2025-07-31 15:10:32"}
{"code":"23505","constraint":"pg_class_relname_nsp_index","detail":"Key (relname, relnamespace)=(subscription_plans_id_seq, 2200) already exists.","file":"nbtinsert.c","length":268,"level":"error","line":"673","message":"Error initializing database tables: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","service":"devquery-backend","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:123:7)","table":"pg_class","timestamp":"2025-07-31 15:14:01"}
{"code":"23505","constraint":"pg_class_relname_nsp_index","detail":"Key (relname, relnamespace)=(subscription_plans_id_seq, 2200) already exists.","file":"nbtinsert.c","length":268,"level":"error","line":"673","message":"Error initializing database tables: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","service":"devquery-backend","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:123:7)","table":"pg_class","timestamp":"2025-07-31 15:14:01"}
{"code":"23505","constraint":"pg_class_relname_nsp_index","detail":"Key (relname, relnamespace)=(admins_id_seq, 2200) already exists.","file":"nbtinsert.c","length":256,"level":"error","line":"673","message":"Error initializing database tables: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","service":"devquery-backend","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:66:7)","table":"pg_class","timestamp":"2025-07-31 15:45:53"}
{"code":"23505","constraint":"pg_class_relname_nsp_index","detail":"Key (relname, relnamespace)=(admins_id_seq, 2200) already exists.","file":"nbtinsert.c","length":256,"level":"error","line":"673","message":"Error initializing database tables: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"","name":"error","routine":"_bt_check_unique","schema":"pg_catalog","service":"devquery-backend","severity":"ERROR","stack":"error: duplicate key value violates unique constraint \"pg_class_relname_nsp_index\"\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:66:7)","table":"pg_class","timestamp":"2025-07-31 15:45:53"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:45:53"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:47:21"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:47:21"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:47:21"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:49:57"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:49:57"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:49:57"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at c:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (c:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:50:04"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at c:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (c:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:50:04"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at c:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (c:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:50:04"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:50:31"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:50:31"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:50:31"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:51:51"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:51:51"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:51:51"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:53:26"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:53:26"}
{"code":"42703","file":"tablecmds.c","length":141,"level":"error","line":"11911","message":"Error initializing database tables: column \"user_id\" referenced in foreign key constraint does not exist","name":"error","routine":"transformColumnNameList","service":"devquery-backend","severity":"ERROR","stack":"error: column \"user_id\" referenced in foreign key constraint does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.initializeTables (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:102:7)","timestamp":"2025-07-31 15:53:26"}
{"level":"error","message":"User login failed: Invalid credentials","service":"devquery-backend","stack":"Error: Invalid credentials\n    at UserManager.loginUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:161:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async login (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\authController.js:87:24)","timestamp":"2025-07-31 21:29:01"}
{"level":"error","message":"Login error: Invalid credentials","service":"devquery-backend","stack":"Error: Invalid credentials\n    at UserManager.loginUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:161:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async login (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\authController.js:87:24)","timestamp":"2025-07-31 21:29:01"}
{"level":"error","message":"User login failed: Invalid credentials","service":"devquery-backend","stack":"Error: Invalid credentials\n    at UserManager.loginUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:161:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async login (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\authController.js:87:24)","timestamp":"2025-07-31 21:30:21"}
{"level":"error","message":"Login error: Invalid credentials","service":"devquery-backend","stack":"Error: Invalid credentials\n    at UserManager.loginUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:161:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async login (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\authController.js:87:24)","timestamp":"2025-07-31 21:30:21"}
{"level":"error","message":"User login failed: Invalid credentials","service":"devquery-backend","stack":"Error: Invalid credentials\n    at UserManager.loginUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:180:15)\n    at async login (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\authController.js:87:24)","timestamp":"2025-07-31 21:30:42"}
{"level":"error","message":"Login error: Invalid credentials","service":"devquery-backend","stack":"Error: Invalid credentials\n    at UserManager.loginUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:180:15)\n    at async login (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\authController.js:87:24)","timestamp":"2025-07-31 21:30:42"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:03:25"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:03:25"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:03:26"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:03:26"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:17:46"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:17:46"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:17:47"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:17:47"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:38:39"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:38:39"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:45:08"}
{"level":"error","message":"Authentication failed: jwt malformed","name":"JsonWebTokenError","service":"devquery-backend","stack":"JsonWebTokenError: jwt malformed\n    at module.exports [as verify] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\jsonwebtoken\\verify.js:70:17)\n    at authenticateUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\middleware\\auth.js:19:25)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:175:3)\n    at router (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\express\\lib\\router\\layer.js:95:5)","timestamp":"2025-08-31 16:48:35"}
{"level":"error","message":"Login error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","service":"devquery-backend","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.loginUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:148:20)\n    at async login (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\authController.js:88:24)","timestamp":"2025-09-12 21:41:26"}
{"level":"error","message":"Login error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string","service":"devquery-backend","stack":"Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.loginUser (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:148:20)\n    at async login (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\authController.js:88:24)","timestamp":"2025-09-12 21:41:33"}
{"code":"28P01","file":"auth.c","length":99,"level":"error","line":"324","message":"Database connection test failed: password authentication failed for user \"dev\"","name":"error","routine":"auth_failed","service":"devquery-backend","severity":"FATAL","stack":"error: password authentication failed for user \"dev\"\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async DatabaseConnectionManager.createPostgreSQLConnection (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\utils\\DatabaseConnectionManager.js:50:20)\n    at async DatabaseConnectionManager.createConnection (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\utils\\DatabaseConnectionManager.js:254:16)\n    at async testConnection (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\databaseController.js:74:26)","timestamp":"2025-09-13 15:54:17"}
{"code":"28P01","file":"auth.c","length":99,"level":"error","line":"324","message":"Database connection test failed: password authentication failed for user \"dev\"","name":"error","routine":"auth_failed","service":"devquery-backend","severity":"FATAL","stack":"error: password authentication failed for user \"dev\"\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg-pool\\index.js:45:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async DatabaseConnectionManager.createPostgreSQLConnection (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\utils\\DatabaseConnectionManager.js:50:20)\n    at async DatabaseConnectionManager.createConnection (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\utils\\DatabaseConnectionManager.js:254:16)\n    at async testConnection (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\databaseController.js:74:26)","timestamp":"2025-09-13 15:54:28"}
{"code":"42P01","file":"parse_relation.c","length":124,"level":"error","line":"1452","message":"Connection tracking failed: relation \"user_database_connections\" does not exist","name":"error","position":"22","routine":"parserOpenTable","service":"devquery-backend","severity":"ERROR","stack":"error: relation \"user_database_connections\" does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.trackConnection (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:391:7)\n    at async connect (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\databaseController.js:24:7)","timestamp":"2025-09-13 16:01:44"}
{"code":"42P01","file":"parse_relation.c","length":124,"level":"error","line":"1452","message":"Database connection failed: relation \"user_database_connections\" does not exist","name":"error","position":"22","routine":"parserOpenTable","service":"devquery-backend","severity":"ERROR","stack":"error: relation \"user_database_connections\" does not exist\n    at C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\node_modules\\pg\\lib\\client.js:545:17\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserManager.trackConnection (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\models\\UserManager.js:391:7)\n    at async connect (C:\\Users\\shiva\\DevLab\\DevQuery\\auth-backend\\src\\controllers\\databaseController.js:24:7)","timestamp":"2025-09-13 16:01:44"}
